# Generated by Django 5.0.6 on 2024-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
